openapi: "3.0.3"
info:
  title: Tax-free childcare payment integration API
  description: "# Overview
  
  It is a government initiative to encourage more parents to use the tax-free childcare (TFC) allowance available to them. To promote this service we want to make it easier for parents to make payments using the funds in their tax-free childcare account.   


This API allows online cashless payment providers for schools to offer their users the opportunity to use their TFC balance to pay for their childcare through the providers platform.


    There are three different operations involved in this process:\n\
    - Linking the parent's TFC account with their account on the online payment provider platform.
    
    - Checking the balance on the child's TFC account'.
    
    - Making a payment from the child's TFC account to the childcare provider.
    
    Requests are passed to National Savings and Investments (NS&I), who hold the TFC account funds."
  version: 1.0.0
servers:
- url: https://test-api.service.hmrc.gov.uk
  description: Sandbox
- url: https://api.service.hmrc.gov.uk
  description: Production
tags:
- name: Link accounts
- name: Check balance
- name: Make payment
paths: 
  /individuals/tax-free-childcare/payments/link:
   post:
      tags:
      - Link accounts
      summary: Linking the parent's online payment provider account to their TFC account
      description: 
        This endpoint links the parent's TFC account with an account they hold with an online payment provider. This linking will be initiated by the payment provider's platform when offering TFC to the parent as an option to pay for their child's care. The parent will be required to confirm if they want this link to be created. This link is essential if the parent wishes to use TFC within the payment provider's platform.
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                correlation_id:
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This 32 character, hyphen separated alphanumeric string is generated and sent by the online payment provider.
                  type: string
                  example: 12a34567-8b90-1234-c6de-5fghi6j78k90
                epp_unique_customer_id:
                  description: The unique ID assigned to the online payment provider by NS&I. 
                  type: string
                epp_reg_reference:
                  description: The unique ID assigned to the online payment provider when they register with HMRC.
                  type: string
                outbound_child_payment_ref:
                  description: The reference number the parent uses when making payments to the CCP. This number is displayed on the TFC portal, and is used by the CCP to allocate incoming funds to the correct child's account. 
                  type: string
                  example: ABCD12345TFC
                child_date_of_birth:
                  description: The date of birth of the child for whom the link is being made. This extra identity check is used to cross-reference with the child's details held by the online payment provider.  
                  type: string
                  example: YYYY-MM-DD

      responses:
          "200":
            description: Confirmation that a link has been established
            content: 
              application/json:
                schema:
                  type: object
                  properties:
                    correlation_id:
                      type: string
                      description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                    child_full_name:
                      type: string
                      description: The full name of the child whose accounts have been linked. Providing this confirms the link has been successful.

  /individuals/tax-free-childcare/payments/balance:
    post:
      tags:
      - Check balance
      summary: Retrieve the balance of the associated child's TFC account
      description: |
        This endpoint fetches the balance of the associated child's TFC account. The balance of the TFC account consists of the following three different elements:\n\- Paid in by you - The amount of money the parent or guardian has paid into the child's account.\n\- Government top-up - The amount of top-up funds paid in by the government.\n\- Total balance - The sum of the two previous amounts.


      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                correlation_id:
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the onine payment provider.
                  type: string
                epp_unique_customer_id:
                  description: The unique ID assigned to the online payment provider by NS&I. 
                  type: string
                epp_reg_reference:
                  description: The unique ID assigned to the online payment provider when they register with HMRC.
                  type: string
                outbound_child_payment_ref:
                  description: The reference number the parent uses when making payments to the childcare provider. This number is displayed on the TFC portal, and is used by the childcare provider to allocate incoming funds to the correct child's account. 
                  type: string
                  example: ABCD12345TFC
                child_date_of_birth:
                  description: The date of birth of the child for whom the link is being made. This extra identity check is used to cross-reference with the child's details held by the onine payment provider. 
                  type: string
                  example: YYYY-MM-DD
                parent_nino:
                  description: The parent's national insurance number in the format AA123456A. This enables NS&I to identify the parent.
                  type: string
                  example: AB123456C
      responses:
          "200":
            description: Confirmation that a link has been established
            content: 
              application/json:
                schema:
                  type: object
                  properties:
                    correlation_id:
                      type: string
                      description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the EPP.
                    tfc_account_status:
                      type: string
                      description: The full name of the child whose accounts have been linked. Providing this confirms the link has been successful.
                    paid_in_by_you:
                      type: string
                      description: The amount of money paid in to the child's TFC account by the parent or guardian.
                    government_top-up:
                      type: string
                      description: The amount paid in by the government, this amount has cleared and is available to the parent or guardian.
                    total_balance:
                      type: string
                      description: The sum of paid_in_by_you and government_top-up, this is the total amount paid into the account.
                    cleared_funds:
                      type: string
                      description: The total amount of money available to the parent or guardian to use to make payments to childcare providers. This is equal to total_balance minus any uncleared funds from paid_in_by_you.
                    top_up_allowance:
                      type: string
                      description: The remaining amount of government top-up that is available to the parent or guardian for the current quarter. The amount that is paid in to the account by the government depends on what the parent or guardian pays in.


  /individuals/tax-free-childcare/payments:
    post:
      tags:
      - Make payment
      summary: Send payment from the TFC account to the intended recipient
      description: |
        This endpoint sends the selected amount to the intended recipient from the child's TFC account.

      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                correlation_id:
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                  type: string
                epp_unique_customer_id:
                  description: The unique ID assigned to the online payment provider by NS&I. 
                  type: string
                epp_reg_reference:
                  description: The unique ID assigned to the online payment provider when they register with HMRC.
                  type: string
                outbound_child_payment_ref:
                  description: The reference number the parent uses when making payments to the childcare provider. This number is displayed on the TFC portal, and is used by the childcare provider to allocate incoming funds to the correct child's account. 
                  type: string
                  example: ABCD12345TFC
                payment_amount:
                  description: The amount of money the parent or guardian wants to pay the childcare provider from their TFC balance.
                  type: string
                  example: £1234.56
                ccp_reg_reference:
                  description: The unique reference number given to the childcare provider by the childcare regulator (e.g. Ofsted). The online payment provider needs to provide this to HMRC. 
                  type: string
                ccp_postcode:
                  description: The postcode associated with the childcare provider, this enables further verification.
                  type: string
                  example: AB12 3CD
                parent_nino:
                  description: The parent's national insurance number in the format AA123456A. This enables NS&I to identify the parent.
                  type: string
                  example: AB123456C
                payee_type:
                  description: The initial recipient of the funds from the child's TFC account. Depending on the online payment provider's policies, payment may initially go to the childcare provider directly or to the online payment provider for initial processing. There are two options, CCP for the childcare provider and EPP for the online payment provider.
                  type: string
                  enum:
                  - CCP
                  - EPP
      responses:
          "200":
            description: Confirmation the payment was succesful
            content: 
              application/json:
                schema:
                  type: object
                  properties:
                    correlation_id:
                      type: string
                      description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                    payment_reference:
                      type: string
                      description: A unique identifier that is used as confirmation that the payment has been successful. This can be used to track the payment.
                    estimated_payment_date:
                      type: string
                      description: The estimated date the payment will leave the child's TFC account. This is used for audit purposes and to give childcare providers an expectation of when they will receive funds. 
      
components:
  securitySchemes:
    bearerAuth:	
      type: http
      scheme: bearer

security:
  - bearerAuth: []

  
