openapi: 3.0.3
info:
  title: Tax-free Childcare Payment Integration API
  version: '1.0'
  description: |-
    It is a government initiative to encourage more parents to use the tax-free childcare (TFC) allowance available to them. To promote this service we want to make it easier for parents to make payments using the funds in their tax-free childcare account.

    This API allows online cashless payment providers for schools to offer their users the opportunity to use their TFC balance to pay for their childcare through the providers platform.

    There are three different operations involved in this process:\n\
    - Linking the parent's TFC account with their account on the online payment provider platform.
    
    - Checking the balance on the child's TFC account'.
    
    - Making a payment from the child's TFC account to the childcare provider.
    
    Requests are passed to National Savings and Investments (NS&I), who hold the TFC account funds."

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
tags:
  - name: Link accounts
    description: This endpoint links the parent's TFC account with an account they hold with an online payment provider. This linking will be initiated by the payment provider's platform when offering TFC to the parent as an option to pay for their child's care. The parent will be required to confirm if they want this link to be created. This link is essential if the parent wishes to use TFC within the payment provider's platform.
paths:
  /individuals/tax-free-childcare/payments/link:
    post:
      tags:
        - Link accounts
      summary: Linking the parent's online payment provider account to their TFC account
      description:
        This endpoint links the parent's TFC account with an account they hold with an online payment provider. This linking will be initiated by the payment provider's platform when offering TFC to the parent as an option to pay for their child's care. The parent will be required to confirm if they want this link to be created. This link is essential if the parent wishes to use TFC within the payment provider's platform.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                correlation_id:
                  description: A unique key shared between all parties which can be used for tracing and error tracking. This 32 character, hyphen separated alphanumeric string is generated and sent by the online payment provider.
                  type: string
                  example: 12a34567-8b90-1234-c6de-5fghi6j78k90
                epp_unique_customer_id:
                  description: This 11 character, numeric, unique ID is assigned to the online payment provider by NS&I.
                  type: string
                  example: 12345678901
                epp_reg_reference:
                  description: This 16 character alphanumeric unique ID is assigned to the online payment provider when they register with HMRC.
                  type: string
                  example: 1a2b3c4d5e6f7g8h
                outbound_child_payment_ref:
                  description: The reference number the parent uses when making payments to the CCP. This number is displayed on the TFC portal, and is used by the CCP to allocate incoming funds to the correct child's account.
                  type: string
                  example: ABCD12345TFC
                child_date_of_birth:
                  description: The date of birth of the child whose accounts are being linked. This extra identity check is used to cross-reference with the child's details held by the online payment provider.
                  type: string
                  example: YYYY-MM-DD

      responses:
        "200":
          description: Confirmation that a link has been established
          content:
            application/json:
              schema:
                type: object
                properties:
                  correlation_id:
                    type: string
                    description: A unique key shared between all parties which can be used for tracing and error tracking. This is generated and sent by the online payment provider.
                    example: 12a34567-8b90-1234-c6de-5fghi6j78k90
                  child_full_name:
                    type: string
                    description: The full name of the child whose accounts have been linked. Providing this confirms the link has been successful.
                    example: Full Name
      security:
        - userRestricted:
            - tax-free-childcare-payments

components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: >-
        HMRC supports OAuth 2.0 for authenticating user restricted API requests
        using an OAuth 2.0 Bearer Token in the AUTHORIZATION header. See
        https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints
        for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            tax-free-childcare-payment: Access all aspects of Tax Free Childcare Payments API
